[package]
name = "prompt-macro"
version = "1.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.60"
quote = "1.0.36"
proc-macro2 = "1.0.81"
parse-format = "0.1.0"
unindent = "0.2.3" 