name: taiko

on:
    push:
        branches: [master, main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
            - uses: actions-rs/cargo@v1
              with:
                command: build
                args: --release